import type { Favorite, Project, RecentEntry, Snippet } from "./types";

const now = Date.now();
const days = (n: number) => now - n * 86400000;

export const mockProjects: Project[] = [
  {
    id: "p1",
    name: "WorkHub",
    description: "桌面端键盘优先效率工具",
    path: "~/code/workhub",
    gitUrl: "https://github.com/workhub/workhub",
    group: "内部工具/核心",
    sortOrder: 0,
    tags: ["Tauri", "Vue", "TS"],
    favorite: true,
    updatedAt: days(0),
    links: [
      { id: "l1", title: "GitHub 仓库", url: "https://github.com/workhub" },
      { id: "l2", title: "需求文档", url: "https://example.com/roadmap" },
    ],
    commands: [
      { id: "c1", title: "启动开发", command: "pnpm tauri dev" },
      { id: "c2", title: "类型检查", command: "pnpm typecheck" },
    ],
    docs: [{ id: "d1", title: "ROADMAP.md", path: "~/code/workhub/ROADMAP.md" }],
  },
  {
    id: "p2",
    name: "数据中台",
    description: "公司内部 BI 与报表服务",
    path: "~/code/data-platform",
    gitUrl: "",
    group: "公司业务/后端",
    sortOrder: 0,
    tags: ["Node", "Postgres"],
    favorite: false,
    updatedAt: days(1),
    links: [{ id: "l3", title: "Grafana", url: "https://grafana.example.com" }],
    commands: [{ id: "c3", title: "本地启动", command: "make dev" }],
    docs: [],
  },
  {
    id: "p3",
    name: "营销官网",
    description: "品牌官网与博客",
    path: "~/code/marketing-site",
    gitUrl: "",
    group: "公司业务/前端",
    sortOrder: 0,
    tags: ["Next.js"],
    favorite: false,
    updatedAt: days(3),
    links: [],
    commands: [{ id: "c4", title: "构建", command: "pnpm build" }],
    docs: [],
  },
  {
    id: "p4",
    name: "移动端 H5",
    description: "活动落地页集合",
    path: "~/code/h5-activities",
    gitUrl: "",
    group: "个人",
    sortOrder: 0,
    tags: ["Vite", "React"],
    favorite: true,
    updatedAt: days(7),
    links: [],
    commands: [],
    docs: [],
  },
];

export const mockSnippets: Snippet[] = [
  {
    id: "s1",
    title: "查找占用端口的进程",
    category: "shell",
    language: "bash",
    tags: ["排错", "网络"],
    code: "lsof -i :3000\nkill -9 <PID>",
    favorite: true,
    updatedAt: days(0),
  },
  {
    id: "s2",
    title: "撤销最近一次 commit（保留改动）",
    category: "git",
    language: "bash",
    tags: ["git"],
    code: "git reset --soft HEAD^",
    favorite: false,
    updatedAt: days(2),
  },
  {
    id: "s3",
    title: "按表查询行数",
    category: "sql",
    language: "sql",
    tags: ["postgres"],
    code: "SELECT relname, n_live_tup\nFROM pg_stat_user_tables\nORDER BY n_live_tup DESC;",
    favorite: false,
    updatedAt: days(4),
  },
  {
    id: "s4",
    title: "防抖函数",
    category: "代码",
    language: "typescript",
    tags: ["工具函数"],
    code: "export function debounce<T extends (...a: any[]) => void>(fn: T, ms = 200) {\n  let t: ReturnType<typeof setTimeout> | null = null;\n  return (...args: Parameters<T>) => {\n    if (t) clearTimeout(t);\n    t = setTimeout(() => fn(...args), ms);\n  };\n}",
    favorite: true,
    updatedAt: days(1),
  },
  {
    id: "s5",
    title: "邮箱正则",
    category: "正则",
    language: "regex",
    tags: ["校验"],
    code: "/^[\\w.+-]+@[\\w-]+\\.[\\w.-]+$/",
    favorite: false,
    updatedAt: days(10),
  },
  {
    id: "s6",
    title: "Element 主色",
    category: "颜色",
    language: "",
    tags: ["Element", "主色"],
    code: "#409EFF",
    favorite: true,
    updatedAt: days(0),
  },
  {
    id: "s7",
    title: "成功绿",
    category: "颜色",
    language: "",
    tags: ["状态色"],
    code: "#67C23A",
    favorite: false,
    updatedAt: days(2),
  },
  {
    id: "s8",
    title: "文字主色",
    category: "颜色",
    language: "",
    tags: ["中性色", "文字"],
    code: "#303133",
    favorite: false,
    updatedAt: days(3),
  },
  {
    id: "s9",
    title: "右箭头",
    category: "符号",
    language: "",
    tags: ["箭头", "流程"],
    code: "→",
    favorite: true,
    updatedAt: days(0),
  },
  {
    id: "s10",
    title: "勾号",
    category: "符号",
    language: "",
    tags: ["完成", "勾选"],
    code: "✓",
    favorite: false,
    updatedAt: days(1),
  },
  {
    id: "s11",
    title: "火箭",
    category: "符号",
    language: "",
    tags: ["emoji", "发布"],
    code: "🚀",
    favorite: false,
    updatedAt: days(2),
  },
  {
    id: "s12",
    title: "Command 键",
    category: "符号",
    language: "",
    tags: ["Mac", "快捷键"],
    code: "⌘",
    favorite: false,
    updatedAt: days(4),
  },
];

export const mockFavorites: Favorite[] = [
  {
    id: "f1",
    kind: "folder",
    title: "下载目录",
    target: "~/Downloads",
    tags: ["常用"],
    updatedAt: days(0),
  },
  {
    id: "f2",
    kind: "link",
    title: "MDN Web Docs",
    target: "https://developer.mozilla.org",
    tags: ["文档"],
    updatedAt: days(1),
  },
  {
    id: "f3",
    kind: "file",
    title: "周报模板",
    target: "~/Documents/templates/weekly.md",
    tags: ["模板"],
    updatedAt: days(5),
  },
  {
    id: "f4",
    kind: "doc",
    title: "团队 Wiki",
    target: "https://wiki.example.com",
    tags: ["团队"],
    updatedAt: days(2),
  },
];

export const mockRecents: RecentEntry[] = [
  { id: "r1", kind: "project", title: "WorkHub", subtitle: "~/code/workhub", refId: "p1", at: days(0) },
  { id: "r2", kind: "snippet", title: "查找占用端口的进程", subtitle: "shell", refId: "s1", at: days(0) },
  { id: "r3", kind: "command", title: "启动开发", subtitle: "pnpm tauri dev", refId: "c1", at: days(0) },
  { id: "r4", kind: "link", title: "MDN Web Docs", subtitle: "https://developer.mozilla.org", refId: "f2", at: days(1) },
  { id: "r5", kind: "project", title: "数据中台", subtitle: "~/code/data-platform", refId: "p2", at: days(1) },
  { id: "r6", kind: "snippet", title: "防抖函数", subtitle: "代码", refId: "s4", at: days(1) },
  { id: "r7", kind: "folder", title: "下载目录", subtitle: "~/Downloads", refId: "f1", at: days(2) },
];
